[package]
name = "tests"
version = "0.1.2"
authors = ["Oded Leiba <oded@kzencorp.com>"]
edition = "2018"

[dependencies]
hex = "0.3.2"
two-party-eddsa-server = { path = "../server" }
two-party-eddsa-client = { path = "../client" }