[package]
name = "tests"
version = "0.1.1"
authors = ["Oded Leiba <oded@kzencorp.com>"]
edition = "2018"

[dependencies]
two-party-eddsa-server = { path = "../server" }
two-party-eddsa-client = { path = "../client" }